hydra:
  run:
    dir: runs_configs_hydra/arch_${arch}_batchsize_${batch_size}_weights_${encoder_weights}_img_size_${img_size}_augmentations_${use_augmentations}_joint_training_${joint_training}_hood_training_${hood_training}_activation_${activation}

# architecture
arch: resnet18

# dataset
train_split: "train_data.csv" 
val_split: "val_data.csv" 
test_split: "test_data.csv" 
# data preprocessing
preprocessing: True

# trainer
img_size: 674
batch_size: 6
num_workers: 2
epochs: 8
joint_training: True
finetune: True
hood_training: False 
projection_head: True

# model
encoder_weights: imagenet
activation: 'linear'
input_size: ${img_size}


# optimizer
optimizer: adamw
lr: 3.0e-4
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# losses
loss: MSE
use_augmentations: False


# logging
vis_freq: 100
save_freq: 1000
print_freq: 1

# distributed processing
mps_training: False
pin_memory: True

